python generate_matrix_feature.py 0 basic
python generate_matrix_feature.py 1 basic
python generate_matrix_feature.py 2 basic
python generate_matrix_feature.py 3 basic
python generate_matrix_feature.py 4 basic
python generate_matrix_feature.py 0 PreActResNet18
python generate_matrix_feature.py 1 PreActResNet18
python generate_matrix_feature.py 2 PreActResNet18
python generate_matrix_feature.py 3 PreActResNet18
python generate_matrix_feature.py 4 PreActResNet18